title: Vicharanashala
description: Website development for Vicharanashala.
theme: minima

url: "https://vicharanashala.github.io"
baseurl: "/vicharanashala-ai"

header_pages:
  - ourstory.md
  - research.md
  - vichara_logs.md
  - lab_initiatives.md
  - national_initiatives.md
  - vibe.md
  - spandan.md
  - vi-slides.md
  - pes.md
  - hp-dashboard-lti.md
  - Vi-Notes.md
  - contact.md
  - team-members.
  - Vi-Sakha.md

plugins:
  - jekyll-feed
