title: Vicharanashala # - Lab for Education Design
description: Innovations that make learning feel human again.
theme: minima

url: "https://vicharanashala.github.io"
baseurl: "/vicharanashala-ai"

collections:
  projects:
    output: true
    permalink: /projects/:slug/

header_pages:
  - ourstory.md
  - products.md
  - lab_initiatives.md
  - national_initiatives.md
  - vichara_logs.md
  - contact.md
  - team-members.md

plugins:
  - jekyll-feed
